import test from 'node:test';
import assert from 'node:assert/strict';
import {create,update,deal,act,rank,view,bots} from '../game.js';
import {observation,estimateEquity,chooseAction} from '../bots.js';
function seeded(seed=341){return ()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
function table(){const g=create('a','Alice','panda');update(g,'b','join',{name:'Bob',avatar:'shark'});return g;}
test('avatars are validated and visible to other seats',()=>{const g=table();assert.equal(g.players[0].avatar,'panda');assert.equal(g.players[1].avatar,'shark');update(g,'a','avatar',{avatar:'owl'});assert.equal(view(g,'b').players[0].avatar,'owl');assert.throws(()=>update(g,'a','avatar',{avatar:'<script>'}));});
test('fold win tracks actual net result; refill keeps scores; score reset keeps stacks',()=>{const g=table();deal(g);const folded=g.turn;act(g,folded,'fold');const w=g.players.find(p=>!p.folded),l=g.players[folded];assert.equal(w.stats.wins,1);assert.equal(l.stats.wins,0);assert.equal(w.stats.hands,1);assert.equal(g.sessionHands,1);assert.equal(w.stats.net,10);assert.equal(l.stats.net,-10);const scores=g.players.map(p=>p.stats.net);update(g,'a','reset');assert.deepEqual(g.players.map(p=>p.stats.net),scores);assert.ok(g.players.every(p=>p.chips===1000));update(g,'a','resetScores');assert.ok(g.players.every(p=>p.stats.net===0&&p.stats.hands===0&&p.chips===1000));assert.equal(g.sessionHands,0);});
test('split pots count each winning hand once and record ties',()=>{const g=table();deal(g);g.board=[8,9,10,11,12];g.phase='river';g.players[0].cards=[13,14];g.players[1].cards=[26,27];g.players.forEach(p=>{p.bet=20;p.total=20;p.chips=980;});g.pot=40;g.current=20;g.pending=[0,1];g.turn=0;g.acted=[];act(g,0,'call');act(g,1,'call');assert.equal(g.phase,'showdown');for(const p of g.players){assert.equal(p.chips,1000);assert.equal(p.stats.wins,1);assert.equal(p.stats.ties,1);assert.equal(p.stats.hands,1);assert.equal(p.stats.net,0);}});
test('multiple all-in pots do not double-count wins or count refunds as wins',()=>{const g=table();update(g,'c','join',{name:'Cat'});deal(g);g.board=[0,14,28,42,7];g.phase='river';const hands=[[12,25],[11,24],[10,23]];g.players.forEach((p,i)=>{p.cards=hands[i];p.total=[100,200,300][i];p.bet=p.total;p.chips=i===2?700:0;p.startChips=[100,200,1000][i];});g.pot=600;g.current=300;g.pending=[2];g.turn=2;g.acted=[];act(g,2,'call');assert.deepEqual(g.players.map(p=>p.chips),[300,200,800]);assert.deepEqual(g.players.map(p=>p.stats.wins),[1,1,0]);assert.equal(g.players.reduce((s,p)=>s+p.stats.net,0),0);});
test('fast evaluator handles multiple trips, three pairs, flush kickers and wheels',()=>{assert.deepEqual(rank([12,25,38,11,24,37,0]),[6,14,13]);assert.deepEqual(rank([12,25,11,24,10,23,9]),[2,14,13,12]);assert.deepEqual(rank([12,9,7,5,2,0,25]),[5,14,11,9,7,4]);assert.deepEqual(rank([12,13,27,41,3,8,10]),[4,5]);});
function riverObservation(){return {cards:[12,11],board:[10,9,8,13,14],phase:'river',seat:0,dealer:0,chips:1000,bet:0,total:100,pot:200,current:0,minRaise:20,canRaise:true,difficulty:'standard',style:'balanced',players:[{folded:false,chips:1000,bet:0,total:100,action:''},{folded:false,chips:1000,bet:0,total:100,action:''}]};}
test('equity recognizes unbeatable hands and shared-board ties',()=>{let o=riverObservation();assert.equal(estimateEquity(o,100,seeded()),1);o.cards=[13,14];o.board=[8,9,10,11,12];assert.equal(estimateEquity(o,100,seeded()),.5);});
test('bots value-bet the nuts, fold weak hands to expensive calls, and check free',()=>{let o=riverObservation();assert.equal(chooseAction(o,{rng:()=>.5,samples:100}).type,'raise');o.cards=[0,14];o.board=[12,24,36,48,7];o.current=900;o.players[1].total=1000;o.pot=1100;o.canRaise=false;assert.equal(chooseAction(o,{rng:seeded(),samples:400}).type,'fold');o.current=0;assert.equal(chooseAction(o,{rng:seeded(),samples:100}).type,'call');});
test('bot observations and decisions are unchanged by secret cards or deck order',()=>{const g=table();deal(g);const before=observation(g,0);g.players[1].cards=[0,1];g.deck.reverse();const after=observation(g,0);assert.deepEqual(after,before);assert.equal('deck' in after,false);assert.ok(after.players.every(p=>!('cards' in p)));assert.deepEqual(chooseAction(before,{rng:seeded(),samples:100}),chooseAction(after,{rng:seeded(),samples:100}));});
test('all difficulty levels can finish complete tables with legal actions and balanced scores',()=>{for(const difficulty of ['easy','standard','challenging']){const g=create('a','Alice');for(let n=0;n<5;n++)update(g,'a','bot');update(g,'a','difficulty',{difficulty});for(let hand=0;hand<12;hand++){if(g.players.filter(p=>p.chips>0).length<2)update(g,'a','reset');update(g,'a','deal');let steps=0;while(g.phase!=='showdown'&&steps++<300){if(g.players[g.turn].bot)bots(g);else update(g,'a','call');}assert.equal(g.phase,'showdown');assert.equal(g.players.reduce((s,p)=>s+p.chips,0),6000);assert.equal(g.players.reduce((s,p)=>s+p.stats.net,0),0);}assert.equal(g.sessionHands,12);}});
