import { useState,useEffect,useRef } from 'react';
const suits=['♣','♦','♥','♠'],faces=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
function Card({c}){return <span className={'card '+(c===null?'back':([1,2].includes(Math.floor(c/13))?'red':''))} aria-label={c===null?'Hidden card':faces[c%13]+' '+suits[Math.floor(c/13)]}>{c===null?'♠':<><b>{faces[c%13]}</b><span>{suits[Math.floor(c/13)]}</span></>}</span>}
export default function Poker(){
 const [name,setName]=useState(''),[code,setCode]=useState(''),[game,setGame]=useState(null),[you,setYou]=useState(''),[version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[amount,setAmount]=useState(40),[light,setLight]=useState(false),[copied,setCopied]=useState(false);const token=useRef('');
 useEffect(()=>{token.current=localStorage.getItem('poker-token')||crypto.randomUUID();localStorage.setItem('poker-token',token.current);setName(localStorage.getItem('poker-name')||'');setCode(new URLSearchParams(location.search).get('table')||'');},[]);
 async function load(){try{let r=await fetch('/api/table?code='+code,{headers:{'x-player-token':token.current}}),d=await r.json();if(r.ok){setGame(d.game);setYou(d.you);setVersion(d.version);}else setError(d.error);}catch{setError('Connection lost. Reconnecting…');}}
 useEffect(()=>{if(!game||!code)return;let t=setInterval(load,1500);return()=>clearInterval(t);},[code,!!game]);
 async function action(a,extra={}){setBusy(true);setError('');try{let r=await fetch('/api/table',{method:'POST',headers:{'Content-Type':'application/json','x-player-token':token.current},body:JSON.stringify({action:a,code,version,name,...extra})}),d=await r.json();if(!r.ok){setError(d.error);if(game)await load();return;}if(d.code){setCode(d.code);history.replaceState(null,'','?table='+d.code);}setGame(d.game);setYou(d.you);setVersion(d.version||0);localStorage.setItem('poker-name',name);}catch{setError('Unable to connect. Please try again.');}finally{setBusy(false);}}
 let me=game?.players.find((p)=>p.id===you),myTurn=game?.turn===game?.players.findIndex((p)=>p.id===you)&&game?.turn>=0,between=game&&['waiting','showdown'].includes(game.phase),host=game?.host===you,call=me?Math.max(0,game.current-me.bet)||0:0,min=game?(game.current||0)+(game.minRaise||20):40,max=me?me.chips+me.bet:0,raiseOK=myTurn&&max>game.current&&!game.acted?.includes(game.players.findIndex((p)=>p.id===you));
 useEffect(()=>{setAmount(Math.min(min,max));},[min,max,game?.turn]);
 return <main className={light?'light':''}><header><a href="/" className="brand">♠ <span>Poker <i>with friends</i></span></a><button className="subtle" onClick={()=>setLight(!light)}>{light?'Dark table':'Light table'}</button></header>
 {!game?<section className="entry"><div className="eyebrow">TAKE A SEAT</div><h1>A good hand.<br/>Better company.</h1><p>Texas Hold’em for up to six players. Invite your friends or play against bots.</p><label>Your name<input maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></label><button className="primary" disabled={busy||!name.trim()} onClick={()=>action('create')}>Open a table</button><div className="join"><label>Have an invite?<input value={code} maxLength={8} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Table code"/></label><button disabled={busy||!code||!name.trim()} onClick={()=>action('join')}>Join table</button></div><small>Play-money chips only · Blinds 10 / 20 · 1,000 starting chips</small>{error&&<p role="alert" className="error">{error}</p>}</section>:<>
 <div className="tablebar"><div><span className="eyebrow">PRIVATE TABLE</span><h1>{code} <span className="hand">Hand {game.hand}</span></h1></div><button onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'?table='+code);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setError('Copy the address from your browser to invite friends.');}}}>{copied?'Link copied':'Copy invite link'}</button></div>
 <div className="workspace"><section className="play"><div className="felt"><div className="table-title">TEXAS HOLD’EM <span>10 / 20</span></div><div className="seats">{Array.from({length:6},(_,i)=>{let p=game.players[i];return <div key={i} className={'seat seat'+i+' '+(game.turn===i?'active':'')+' '+(p?.folded?'folded':'')}>
 {p?<><div className="player"><span className="avatar">{p.bot?'♟':'♙'}</span><div><strong>{p.name}{p.id===you?' (you)':''}</strong><span>{p.chips.toLocaleString()} chips</span></div>{game.dealer===i&&<b className="dealer" title="Dealer">D</b>}</div><div className="hole">{p.cards.map((c,k)=><Card key={k} c={c}/>)}</div><div className="seat-status">{game.turn===i?(p.id===you?'Your turn':'Thinking…'):p.action||'Ready'}{p.bet>0&&` · ${p.bet} bet`}{p.chips===0&&!p.folded&&p.cards.length>0?' · All-in':''}</div>{host&&between&&p.id!==you&&<button className="remove" onClick={()=>action('remove',{target:p.id})} aria-label={'Remove '+p.name}>Remove</button>}</>:<div className="empty">Seat {i+1}<span>Waiting for a friend</span></div>}</div>})}</div>
 <div className="community"><div className="pot">{game.phase==='showdown'?'FINAL POT':'POT'} <strong>{game.pot.toLocaleString()}</strong></div><div className="board">{Array.from({length:5},(_,i)=>game.board[i]!==undefined?<Card key={i} c={game.board[i]}/>:<span key={i} className="card placeholder">{i<3?'FLOP':i===3?'TURN':'RIVER'}</span>)}</div><div className="phase">{game.phase==='waiting'?'Waiting for players':game.phase==='showdown'?'Hand complete':game.phase}</div></div></div>
 <section className="controls">{between?<><div><strong>{game.phase==='waiting'?'Ready when you are.':'The chips are settled.'}</strong><p>{host?'Add friends or bots, then deal.':'The host can deal the next hand.'}</p></div>{host&&<div className="actions"><button disabled={busy||game.players.length>=6} onClick={()=>action('bot')}>Add bot</button><button className="primary" disabled={busy||game.players.filter((p)=>p.chips>0).length<2} onClick={()=>action('deal')}>{game.hand?'Deal next hand':'Deal the cards'}</button></div>}</>:<><div><strong>{myTurn?'Your move.':`${game.players[game.turn]?.name||'Table'} is playing.`}</strong><p>{myTurn?(call?`${call} chips to call.`:'You can check or bet.'):'Your cards stay private. The table updates automatically.'}</p></div><div className="actions"><button disabled={!myTurn||busy} onClick={()=>action('fold')}>Fold</button><button disabled={!myTurn||busy} onClick={()=>action('call')}>{call?`Call ${Math.min(call,me?.chips||0)}`:'Check'}</button><label className="bet-label">Total bet<input type="number" min={Math.min(min,max)} max={max} step="1" value={amount} disabled={!raiseOK||busy} onChange={e=>setAmount(Number(e.target.value))}/></label><button className="primary" disabled={!raiseOK||busy||amount>max||amount<=game.current||(amount<min&&amount!==max)} onClick={()=>action('raise',{amount})}>{amount===max?'All-in':game.current?'Raise':'Bet'}</button></div></>}{error&&<p role="alert" className="error">{error}</p>}</section></section>
 <aside><section className="panel"><div className="eyebrow">TABLE ACTIVITY</div><h2>The hand so far</h2><div className="log" aria-live="polite">{game.log.slice().reverse().map((line,i)=><p key={i}>{line}</p>)}</div></section><details className="panel"><summary>How to play</summary><p>Make your best five-card hand using your two cards and the five community cards. Check when no bet is owed, call to match a bet, raise, or fold.</p><p>Minimum raises match the last full raise. Short all-ins do not reopen raising. Side pots and ties are settled automatically.</p><p>Strongest to weakest: straight flush, four of a kind, full house, flush, straight, three of a kind, two pair, pair, high card.</p><p>Bots use simple check/call/fold decisions. Invite links work for people who have access to this app.</p></details>{host&&between&&<button className="reset" disabled={busy} onClick={()=>action('reset')}>Reset all stacks to 1,000</button>}</aside></div><footer>Play-money poker · No purchases, wagers, or cash prizes</footer></>}
 </main>;
}
