import { useState,useEffect,useRef } from 'react';
import { avatars, avatarFor } from '../avatars.js';
const signed=n=>(n>0?'+':'')+n.toLocaleString();
function AvatarPicker({value,onChange,disabled=false}){return <div className="avatars" role="group" aria-label="Choose your avatar">{avatars.map(a=><button key={a.id} type="button" aria-label={a.label} aria-pressed={value===a.id} title={a.label} disabled={disabled} onClick={()=>onChange(a.id)}>{a.icon}</button>)}</div>;}
function Scoreboard({game,you}){const standings=[...game.players].sort((a,b)=>b.stats.net-a.stats.net||b.chips-a.chips);return <section className="panel scoreboard"><div className="score-heading"><div><div className="eyebrow">SESSION SCOREBOARD</div><h2>Who's ahead?</h2></div><span>{game.sessionHands} completed {game.sessionHands===1?'hand':'hands'}</span></div><div className="score-scroll"><table><caption className="sr-only">Session results for players currently at the table, ordered by net chips won.</caption><thead><tr><th scope="col">Player</th><th scope="col">Chips</th><th scope="col">Net won</th><th scope="col">Hands</th><th scope="col">Wins</th><th scope="col">Ties</th><th scope="col">Last hand</th></tr></thead><tbody>{standings.map((p,i)=><tr key={p.id} className={p.id===you?'my-score':''}><th scope="row"><span className="score-place">{i+1}</span><span className="score-avatar" aria-hidden="true">{avatarFor(p.avatar).icon}</span>{p.name}{p.id===you?' (you)':''}{p.bot&&<small>Bot · {p.style}</small>}</th><td>{p.chips.toLocaleString()}</td><td className={p.stats.net>0?'gain':p.stats.net<0?'loss':''}>{signed(p.stats.net)}</td><td>{p.stats.hands}</td><td>{p.stats.wins}</td><td>{p.stats.ties}</td><td className={p.stats.lastNet>0?'gain':p.stats.lastNet<0?'loss':''}>{signed(p.stats.lastNet)}</td></tr>)}</tbody></table></div><p className="score-note">Net won counts completed hands only. A win means taking any pot, including a split; ties count hands with a shared pot. Refilling stacks keeps your score.</p></section>;} 
function TableChat({messages,onSend}){
 const [draft,setDraft]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState('');const list=useRef(null);
 useEffect(()=>{if(list.current)list.current.scrollTop=list.current.scrollHeight;},[messages.length]);
 async function submit(e){e.preventDefault();if(!draft.trim()||sending)return;setSending(true);setError('');try{const problem=await onSend(draft);if(problem)setError(problem);else setDraft('');}finally{setSending(false);}}
 return <section className="panel chat-panel"><div className="eyebrow">AT THE TABLE</div><h2>Chat</h2><div className="chat-list" ref={list} role="log" aria-label="Table messages" aria-live="polite" aria-relevant="additions">{messages.length?messages.map(m=><article className="chat-message" key={m.id}><div><span aria-hidden="true">{avatarFor(m.avatar).icon}</span> <strong>{m.name}</strong><time dateTime={new Date(m.time).toISOString()}>{new Date(m.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div><p>{m.text}</p></article>):<p className="chat-empty">Say hello to your table.</p>}</div><form onSubmit={submit}><label className="sr-only" htmlFor="chat-message">Message to the table</label><textarea id="chat-message" rows="2" maxLength={300} value={draft} placeholder="Message the table…" onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit(e);}}}/><div className="chat-send"><small>{draft.length}/300</small><button type="submit" disabled={sending||!draft.trim()}>{sending?'Sending…':'Send'}</button></div></form>{error&&<p className="error" role="alert">{error}</p>}</section>;
}
const suits=['♣','♦','♥','♠'],faces=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
function Card({c}){return <span className={'card '+(c===null?'back':([1,2].includes(Math.floor(c/13))?'red':''))} aria-label={c===null?'Hidden card':faces[c%13]+' '+suits[Math.floor(c/13)]}>{c===null?'♠':<><b>{faces[c%13]}</b><span>{suits[Math.floor(c/13)]}</span></>}</span>}
export default function Poker(){
 const [name,setName]=useState(''),[code,setCode]=useState(''),[game,setGame]=useState(null),[you,setYou]=useState(''),[version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[amount,setAmount]=useState(40),[light,setLight]=useState(false),[copied,setCopied]=useState(false),[avatar,setAvatar]=useState('fox'),[avatarOpen,setAvatarOpen]=useState(false),[messages,setMessages]=useState([]),[clock,setClock]=useState(null),[tick,setTick]=useState(0);const token=useRef(''),latest=useRef({revision:-1,time:0});
 useEffect(()=>{token.current=localStorage.getItem('poker-token')||crypto.randomUUID();localStorage.setItem('poker-token',token.current);setName(localStorage.getItem('poker-name')||'');setAvatar(localStorage.getItem('poker-avatar')||'fox');setCode(new URLSearchParams(location.search).get('table')||'');},[]);
 function receive(d){
  if(d.revision<latest.current.revision||(d.revision===latest.current.revision&&d.serverNow<latest.current.time))return;
  latest.current={revision:d.revision,time:d.serverNow};setGame(d.game);setYou(d.you);setVersion(d.version);setMessages(d.messages||[]);setClock(d.deadline===null?null:{remaining:d.deadline-d.serverNow,received:performance.now()});
 }
 useEffect(()=>{const timer=setInterval(()=>setTick(performance.now()),250);return()=>clearInterval(timer);},[]);
 async function sendChat(text){try{const r=await fetch('/api/table',{method:'POST',headers:{'Content-Type':'application/json','x-player-token':token.current},body:JSON.stringify({action:'chat',code,text})});const d=await r.json();if(!r.ok)return d.error;receive(d);return '';}catch{return 'Message not sent. Please try again.';}}
 async function load(){try{let r=await fetch('/api/table?code='+code,{headers:{'x-player-token':token.current}}),d=await r.json();if(r.ok){receive(d);}else setError(d.error);}catch{setError('Connection lost. Reconnecting…');}}
 useEffect(()=>{if(!game||!code)return;let t=setInterval(load,1500);return()=>clearInterval(t);},[code,!!game]);
 async function action(a,extra={}){setBusy(true);setError('');try{let r=await fetch('/api/table',{method:'POST',headers:{'Content-Type':'application/json','x-player-token':token.current},body:JSON.stringify({action:a,code,version,name,avatar,...extra})}),d=await r.json();if(!r.ok){setError(d.error);if(game)await load();return;}if(d.code){setCode(d.code);history.replaceState(null,'','?table='+d.code);}receive(d);localStorage.setItem('poker-name',name);if(a==='avatar'){setAvatar(extra.avatar);localStorage.setItem('poker-avatar',extra.avatar);setAvatarOpen(false);}else localStorage.setItem('poker-avatar',avatar);}catch{setError('Unable to connect. Please try again.');}finally{setBusy(false);}}
 const seconds=clock?Math.max(0,Math.ceil((clock.remaining-Math.max(0,tick-clock.received))/1000)):null,expired=seconds===0;
 let me=game?.players.find((p)=>p.id===you),myTurn=game?.turn===game?.players.findIndex((p)=>p.id===you)&&game?.turn>=0,between=game&&['waiting','showdown'].includes(game.phase),host=game?.host===you,call=me?Math.max(0,game.current-me.bet)||0:0,min=game?(game.current||0)+(game.minRaise||20):40,max=me?me.chips+me.bet:0,raiseOK=myTurn&&max>game.current&&!game.acted?.includes(game.players.findIndex((p)=>p.id===you));
 useEffect(()=>{setAmount(Math.min(min,max));},[min,max,game?.turn]);
 return <main className={light?'light':''}><header><a href="/" className="brand">♠ <span>Poker <i>with friends</i></span></a><button className="subtle" onClick={()=>setLight(!light)}>{light?'Dark table':'Light table'}</button></header>
 {!game?<section className="entry"><div className="eyebrow">TAKE A SEAT</div><h1>A good hand.<br/>Better company.</h1><p>Texas Hold’em for up to six players. Invite your friends or play against bots.</p><label>Your name<input maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></label><div className="avatar-label">Choose your avatar</div><AvatarPicker value={avatar} onChange={setAvatar} disabled={busy}/><button className="primary" disabled={busy||!name.trim()} onClick={()=>action('create')}>Open a table</button><div className="join"><label>Have an invite?<input value={code} maxLength={8} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Table code"/></label><button disabled={busy||!code||!name.trim()} onClick={()=>action('join')}>Join table</button></div><small>Play-money chips only · Blinds 10 / 20 · 1,000 starting chips</small>{error&&<p role="alert" className="error">{error}</p>}</section>:<>
 <div className="tablebar"><div><span className="eyebrow">PRIVATE TABLE</span><h1>{code} <span className="hand">Hand {game.hand}</span></h1></div><button onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'?table='+code);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setError('Copy the address from your browser to invite friends.');}}}>{copied?'Link copied':'Copy invite link'}</button></div>
 <>{avatarOpen&&<section className="panel table-avatar-picker"><div className="picker-heading"><strong>Choose your avatar</strong><button className="subtle" onClick={()=>setAvatarOpen(false)}>Close</button></div><AvatarPicker value={me?.avatar||avatar} disabled={busy} onChange={v=>action('avatar',{avatar:v})}/></section>}</><div className="workspace"><section className="play"><div className="felt"><div className="table-title">TEXAS HOLD’EM <span>10 / 20</span></div><div className="seats">{Array.from({length:6},(_,i)=>{let p=game.players[i];return <div key={i} className={'seat seat'+i+' '+(game.turn===i?'active':'')+' '+(p?.folded?'folded':'')}>
 {p?<><div className="player"><button className="avatar" title={p.id===you?"Change your avatar":avatarFor(p.avatar).label} aria-label={p.id===you?"Change your avatar":avatarFor(p.avatar).label} disabled={p.id!==you||busy} onClick={()=>setAvatarOpen(!avatarOpen)}>{avatarFor(p.avatar).icon}</button><div><strong>{p.name}{p.id===you?' (you)':''}</strong><span>{p.chips.toLocaleString()} chips</span>{p.bot&&<span className="bot-label">Bot · {p.style}</span>}</div>{game.dealer===i&&<b className="dealer" title="Dealer">D</b>}</div><div className="hole">{p.cards.map((c,k)=><Card key={k} c={c}/>)}</div><div className="seat-status">{game.turn===i?(p.id===you?'Your turn':'Thinking…'):p.action||'Ready'}{game.turn===i&&seconds!==null&&` · ${seconds}s`}{p.bet>0&&` · ${p.bet} bet`}{p.chips===0&&!p.folded&&p.cards.length>0?' · All-in':''}</div>{host&&between&&p.id!==you&&<button className="remove" onClick={()=>action('remove',{target:p.id})} aria-label={'Remove '+p.name}>Remove</button>}</>:<div className="empty">Seat {i+1}<span>Waiting for a friend</span></div>}</div>})}</div>
 <div className="community"><div className="pot">{game.phase==='showdown'?'FINAL POT':'POT'} <strong>{game.pot.toLocaleString()}</strong></div><div className="board">{Array.from({length:5},(_,i)=>game.board[i]!==undefined?<Card key={i} c={game.board[i]}/>:<span key={i} className="card placeholder">{i<3?'FLOP':i===3?'TURN':'RIVER'}</span>)}</div><div className="phase">{game.phase==='waiting'?'Waiting for players':game.phase==='showdown'?'Hand complete':game.phase}</div></div></div>
 <section className="controls">{between?<><div><strong>{game.phase==='waiting'?'Ready when you are.':'The chips are settled.'}</strong><p>{host?'Add friends or bots, then deal.':'The host can deal the next hand.'}</p></div>{host&&<div className="actions"><label className="difficulty-label">Turn timer<select value={game.turnSeconds} disabled={busy} onChange={e=>action('timer',{seconds:Number(e.target.value)})}><option value={15}>15 seconds</option><option value={30}>30 seconds</option><option value={60}>60 seconds</option><option value={0}>Off</option></select></label><label className="difficulty-label">Bot difficulty<select value={game.botDifficulty} disabled={busy} onChange={e=>action('difficulty',{difficulty:e.target.value})}><option value="easy">Easy</option><option value="standard">Standard</option><option value="challenging">Challenging</option></select></label><button disabled={busy||game.players.length>=6} onClick={()=>action('bot')}>Add bot</button><button className="primary" disabled={busy||game.players.filter((p)=>p.chips>0).length<2} onClick={()=>action('deal')}>{game.hand?'Deal next hand':'Deal the cards'}</button></div>}</>:<><div><strong>{myTurn?'Your move.':`${game.players[game.turn]?.name||'Table'} is playing.`}</strong><div className={'turn-clock '+(seconds!==null&&seconds<=10?'urgent':'')} role="timer" aria-label="Time remaining for the active player">{seconds===null?'Timer off':seconds===0?'Resolving timeout…':`${seconds}s remaining`}</div><small className="timeout-note">{seconds!==null?'Timeout: check if possible, otherwise fold.':''}</small><p>{myTurn?(call?`${call} chips to call.`:'You can check or bet.'):'Your cards stay private. The table updates automatically.'}</p></div><div className="actions"><button disabled={!myTurn||busy||expired} onClick={()=>action('fold')}>Fold</button><button disabled={!myTurn||busy||expired} onClick={()=>action('call')}>{call?`Call ${Math.min(call,me?.chips||0)}`:'Check'}</button><label className="bet-label">Total bet<input type="number" min={Math.min(min,max)} max={max} step="1" value={amount} disabled={!raiseOK||busy||expired} onChange={e=>setAmount(Number(e.target.value))}/></label><button className="primary" disabled={!raiseOK||busy||expired||amount>max||amount<=game.current||(amount<min&&amount!==max)} onClick={()=>action('raise',{amount})}>{amount===max?'All-in':game.current?'Raise':'Bet'}</button></div></>}{error&&<p role="alert" className="error">{error}</p>}</section><Scoreboard game={game} you={you}/></section>
 <aside><TableChat messages={messages} onSend={sendChat}/><section className="panel"><div className="eyebrow">TABLE ACTIVITY</div><h2>The hand so far</h2><div className="log" aria-live="polite">{game.log.slice().reverse().map((line,i)=><p key={i}>{line}</p>)}</div></section><details className="panel"><summary>How to play</summary><p>Make your best five-card hand using your two cards and the five community cards. Check when no bet is owed, call to match a bet, raise, or fold.</p><p>Minimum raises match the last full raise. Short all-ins do not reopen raising. Side pots and ties are settled automatically.</p><p>Strongest to weakest: straight flush, four of a kind, full house, flush, straight, three of a kind, two pair, pair, high card.</p><p>Standard and Challenging bots estimate their chance of winning, compare the cost of calling, and mix bets, raises, folds, and occasional bluffs. Challenging bots also adjust for opponents’ visible raises. They never see your hidden cards.</p><p>The host can change difficulty between hands. Easy uses the original simple strategy. These are practice bots, not professional poker solvers.</p><p>The host sets the turn timer between hands. When time runs out, the server checks if no chips are owed; otherwise it folds. Chatting, refreshing, and changing avatars do not extend your turn.</p><p>Click your avatar to change it. Share the invite link so friends can join.</p></details>{host&&between&&<div className="reset-controls"><button className="reset" disabled={busy} onClick={()=>{if(window.confirm('Refill all stacks to 1,000? Session scores will be kept.'))action('reset');}}>Refill stacks to 1,000</button><button className="reset" disabled={busy} onClick={()=>{if(window.confirm('Clear all session scores? Chip stacks will stay the same.'))action('resetScores');}}>Reset session scores</button></div>}</aside></div><footer>Play-money poker · No purchases, wagers, or cash prizes</footer></>}
 </main>;
}
